name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt install build-essential meson ninja-build python3-pip python3-setuptools libkpathsea-dev texlive-binaries
        pip3 install --upgrade pip
        pip3 install meson==0.55.3 --user
    - name: Build libdvi
      run: |
        meson setup builddir
        meson compile -C builddir
